server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(isA/3GQJV5WNjdgpiWWKxw4McdGiL6XmLKgJfYe9Zz5W+GKwEACYkiFwqJfto9hFbUOOTRptal6x4SX5mHVsjWyDiEBBuYl8l58V1wkPkssJHYUhTp7jcX1xVqLD4VA9)
    username: ENC(pcAfOpGOtXRjXyqhuOGfYTIIfnQcWwYx)
    password: ENC(Zqj59ySaK+PrFpXHL7M0IFWcW5UeYuZ0)
logging:
  level:
    root: info

mybatis:
  type-aliases-package: com.liivtogether.dto
  mapper-locations: classpath:/mybatis/*.xml

# ?? ??(?? ??) ?? ?? ?? ??
#  logging.level.root=info
# ????? ?? ?? ?? ?
# logging.level.gd.fintech.webapp=info
# logging.level.gd.fintech.webapp.controller=debug
# logging.level.gd.fintech.webapp.mapper=trace


# User Define
app:
  imgdir: file:///c:/project/uimg/
  logdir: file:///c:/project/logs/
  kakaorest: ENC(0DoCTcIuytz/+jWIBW6u4NyyXOdNTSk4aXXIKV39DyhDbNmu0gjBpGWq0Y0q/BDW)
  kakaojs: ENC(WbIiCweUuB9CHl/lv/5oo4v+Gm8zY27ThCB9g01bvo94uByfVGRm+se5Rk+jaEB8)
 
serviceserver: https://49.50.166.191:8443
 